// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelGuide.Data;

#nullable disable

namespace TravelGuide.Migrations
{
    [DbContext(typeof(TravelGuideContext))]
    [Migration("20260617112355_AddCoordinates")]
    partial class AddCoordinates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TravelGuide.Models.Entities.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Agencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactInfo = "info@travelworld.com, +7 (495) 123-45-67",
                            Description = "Крупнейший туроператор с 15-летним опытом",
                            Name = "TravelWorld",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            ContactInfo = "contact@suntour.ru, +7 (495) 987-65-43",
                            Description = "Специализация на пляжном отдыхе",
                            Name = "SunTour",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            ContactInfo = "info@adventure.club, +7 (495) 555-44-33",
                            Description = "Экстремальный и приключенческий туризм",
                            Name = "AdventureClub",
                            Rating = 4.7000000000000002
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Анталья"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Стамбул"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Хургада"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Шарм-эль-Шейх"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "Рим"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            Name = "Венеция"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 4,
                            Name = "Барселона"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 4,
                            Name = "Мадрид"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 5,
                            Name = "Паттайя"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 5,
                            Name = "Пхукет"
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Безвизовая страна. Тёплый климат, средиземноморское побережье.",
                            Name = "Турция"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Безвизовая страна. Песчаные пляжи, Красное море.",
                            Name = "Египет"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Требуется виза Шенген. Богатая история, кухня, искусство.",
                            Name = "Италия"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Требуется виза Шенген. Пляжи, архитектура, фламенко.",
                            Name = "Испания"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Виза по прилёту. Тропический климат, буддийские храмы.",
                            Name = "Таиланд"
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.FavoriteTour", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "TourId");

                    b.HasIndex("TourId");

                    b.ToTable("FavoriteTours");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DistanceToBeach")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DistanceToCenter")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("MealType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Роскошный отель премиум-класса",
                            DistanceToBeach = 100,
                            Latitude = 36.856699999999996,
                            Longitude = 31.057400000000001,
                            MealType = 4,
                            Name = "Rixos Premium Belek",
                            PricePerNight = 15000m,
                            Stars = 5
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Семейный отель с аквапарком",
                            DistanceToBeach = 50,
                            Latitude = 36.860100000000003,
                            Longitude = 30.789300000000001,
                            MealType = 4,
                            Name = "Titanic Deluxe Lara",
                            PricePerNight = 12000m,
                            Stars = 5
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Description = "Отель на берегу Красного моря",
                            DistanceToBeach = 0,
                            Latitude = 27.257899999999999,
                            Longitude = 33.811599999999999,
                            MealType = 3,
                            Name = "Hilton Hurghada Plaza",
                            PricePerNight = 10000m,
                            Stars = 5
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Description = "Премиум отель с собственным рифом",
                            DistanceToBeach = 0,
                            Latitude = 27.948599999999999,
                            Longitude = 34.389899999999997,
                            MealType = 4,
                            Name = "Four Seasons Sharm El Sheikh",
                            PricePerNight = 20000m,
                            Stars = 5
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Description = "Отель в историческом центре Рима",
                            Latitude = 41.902799999999999,
                            Longitude = 12.4964,
                            MealType = 1,
                            Name = "Hotel Artemide Rome",
                            PricePerNight = 8000m,
                            Stars = 4
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Description = "Исторический отель у каналов",
                            Latitude = 45.4343,
                            Longitude = 12.338699999999999,
                            MealType = 1,
                            Name = "Hotel Danieli Venice",
                            PricePerNight = 25000m,
                            Stars = 5
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            Description = "Дизайнерский отель у пляжа",
                            DistanceToBeach = 200,
                            Latitude = 41.367400000000004,
                            Longitude = 2.1964999999999999,
                            MealType = 2,
                            Name = "Hotel Arts Barcelona",
                            PricePerNight = 18000m,
                            Stars = 5
                        },
                        new
                        {
                            Id = 8,
                            CityId = 9,
                            Description = "Люкс-отель на реке Чаупхрая",
                            Latitude = 13.7409,
                            Longitude = 100.5423,
                            MealType = 1,
                            Name = "Mandarin Oriental Bangkok",
                            PricePerNight = 15000m,
                            Stars = 5
                        },
                        new
                        {
                            Id = 9,
                            CityId = 10,
                            Description = "Отель на пляже Кататхани",
                            DistanceToBeach = 0,
                            Latitude = 7.8253000000000004,
                            Longitude = 98.2971,
                            MealType = 4,
                            Name = "Katathani Phuket",
                            PricePerNight = 12000m,
                            Stars = 5
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("SightId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Sight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Sights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Duden Park",
                            CityId = 1,
                            Description = "Красивый водопад в парке",
                            Latitude = 36.857500000000002,
                            Longitude = 30.785299999999999,
                            Name = "Водопад Дюден",
                            Type = 6
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza Plateau",
                            CityId = 3,
                            Description = "Древние пирамиды Египта",
                            Latitude = 29.979199999999999,
                            Longitude = 31.1342,
                            Name = "Пирамиды Гизы",
                            Type = 5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Piazza del Colosseo",
                            CityId = 5,
                            Description = "Древнеримский амфитеатр",
                            Latitude = 41.8902,
                            Longitude = 12.4922,
                            Name = "Колизей",
                            Type = 5
                        },
                        new
                        {
                            Id = 4,
                            Address = "Piazza San Marco",
                            CityId = 6,
                            Description = "Шедевр византийской архитектуры",
                            Latitude = 45.4343,
                            Longitude = 12.338699999999999,
                            Name = "Собор Святого Марка",
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "Carrer de Mallorca",
                            CityId = 7,
                            Description = "Шедевр Гауди",
                            Latitude = 41.403599999999997,
                            Longitude = 2.1743999999999999,
                            Name = "Саграда Фамилия",
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Address = "Soi Naklua",
                            CityId = 9,
                            Description = "Уникальный деревянный храм",
                            Latitude = 12.9857,
                            Longitude = 100.8865,
                            Name = "Храм Истины",
                            Type = 4
                        },
                        new
                        {
                            Id = 7,
                            Address = "Nakkerd Hills",
                            CityId = 10,
                            Description = "45-метровая статуя Будды",
                            Latitude = 7.8293999999999997,
                            Longitude = 98.319299999999998,
                            Name = "Большой Будда",
                            Type = 2
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSeasonal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Route")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonalMonths")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TourType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("CountryId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgencyId = 1,
                            CountryId = 1,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Отдых в отеле Rixos Premium Belek по системе всё включено. Прекрасные пляжи, бассейны, SPA.",
                            Duration = 7,
                            IsSeasonal = false,
                            Name = "Турция: Все включено",
                            Price = 65000m,
                            TourType = 2,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AgencyId = 2,
                            CountryId = 2,
                            CreatedDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Дайвинг и сноркелинг на Красном море. Прекрасные коралловые рифы.",
                            Duration = 10,
                            IsSeasonal = false,
                            Name = "Египет: Красное море",
                            Price = 55000m,
                            TourType = 2,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            AgencyId = 1,
                            CountryId = 3,
                            CreatedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Рим, Флоренция, Венеция за 8 дней. Обзорные экскурсии, музеи, дегустации.",
                            Duration = 8,
                            IsSeasonal = false,
                            Name = "Италия: Классика",
                            Price = 85000m,
                            TourType = 1,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 4,
                            AgencyId = 1,
                            CountryId = 4,
                            CreatedDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Архитектура Гауди, пляжи, испанская кухня. Экскурсии с гидом.",
                            Duration = 5,
                            IsSeasonal = false,
                            Name = "Испания: Барселона",
                            Price = 45000m,
                            TourType = 1,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 5,
                            AgencyId = 3,
                            CountryId = 5,
                            CreatedDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Отдых на тропическом острове. Экскурсии к храмам, дайвинг, тайский массаж.",
                            Duration = 14,
                            IsSeasonal = false,
                            Name = "Таиланд: Пхукет",
                            Price = 95000m,
                            TourType = 2,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 6,
                            AgencyId = 2,
                            CountryId = 1,
                            CreatedDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Гранд-базар, Голубая мечеть, дворец Топкапы. Шоппинг и история.",
                            Duration = 4,
                            IsSeasonal = false,
                            Name = "Турция: Стамбул",
                            Price = 35000m,
                            TourType = 1,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 7,
                            AgencyId = 3,
                            CountryId = 2,
                            CreatedDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Пирамиды, Сфинкс, Долина царей. История Древнего Египта.",
                            Duration = 6,
                            IsSeasonal = false,
                            Name = "Египет: Каир и Луксор",
                            Price = 60000m,
                            TourType = 1,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 8,
                            AgencyId = 1,
                            CountryId = 1,
                            CreatedDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Стамбул и Шарм-эль-Шейх. Экскурсии и пляжный отдых.",
                            Duration = 12,
                            IsSeasonal = false,
                            Name = "Комбинированный: Турция+Египет",
                            Price = 110000m,
                            TourType = 3,
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.TourHotel", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("TourId", "HotelId");

                    b.HasIndex("HotelId");

                    b.ToTable("TourHotels");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            HotelId = 1
                        },
                        new
                        {
                            TourId = 2,
                            HotelId = 3
                        },
                        new
                        {
                            TourId = 3,
                            HotelId = 5
                        },
                        new
                        {
                            TourId = 3,
                            HotelId = 6
                        },
                        new
                        {
                            TourId = 4,
                            HotelId = 7
                        },
                        new
                        {
                            TourId = 5,
                            HotelId = 9
                        },
                        new
                        {
                            TourId = 6,
                            HotelId = 2
                        },
                        new
                        {
                            TourId = 7,
                            HotelId = 4
                        },
                        new
                        {
                            TourId = 8,
                            HotelId = 2
                        },
                        new
                        {
                            TourId = 8,
                            HotelId = 4
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.TourSight", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SightId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("TourId", "SightId");

                    b.HasIndex("SightId");

                    b.ToTable("TourSights");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            SightId = 1
                        },
                        new
                        {
                            TourId = 3,
                            SightId = 3
                        },
                        new
                        {
                            TourId = 3,
                            SightId = 4
                        },
                        new
                        {
                            TourId = 4,
                            SightId = 5
                        },
                        new
                        {
                            TourId = 5,
                            SightId = 7
                        },
                        new
                        {
                            TourId = 7,
                            SightId = 2
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@travelguide.com",
                            FullName = "Администратор Системы",
                            IsBlocked = false,
                            PasswordHash = "$2a$11$placeholderWillBeUpdatedOnFirstRun",
                            RegistrationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3
                        });
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Booking", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelGuide.Models.Entities.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuide.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedByUser");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Chat", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.User", "Manager")
                        .WithMany("ManagedChats")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelGuide.Models.Entities.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.City", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.FavoriteTour", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.Tour", "Tour")
                        .WithMany("Favorites")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuide.Models.Entities.User", "User")
                        .WithMany("FavoriteTours")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Hotel", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Message", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuide.Models.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Review", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelGuide.Models.Entities.Sight", "Sight")
                        .WithMany("Reviews")
                        .HasForeignKey("SightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelGuide.Models.Entities.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelGuide.Models.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Sight");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Sight", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.City", "City")
                        .WithMany("Sights")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Tour", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.Agency", "Agency")
                        .WithMany("Tours")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuide.Models.Entities.Country", "Country")
                        .WithMany("Tours")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.TourHotel", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.Hotel", "Hotel")
                        .WithMany("TourHotels")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuide.Models.Entities.Tour", "Tour")
                        .WithMany("TourHotels")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.TourSight", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.Sight", "Sight")
                        .WithMany("TourSights")
                        .HasForeignKey("SightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuide.Models.Entities.Tour", "Tour")
                        .WithMany("TourSights")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sight");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.User", b =>
                {
                    b.HasOne("TravelGuide.Models.Entities.Agency", "Agency")
                        .WithMany("Managers")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Agency", b =>
                {
                    b.Navigation("Managers");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.City", b =>
                {
                    b.Navigation("Hotels");

                    b.Navigation("Sights");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Hotel", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("TourHotels");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Sight", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("TourSights");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.Tour", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("TourHotels");

                    b.Navigation("TourSights");
                });

            modelBuilder.Entity("TravelGuide.Models.Entities.User", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("FavoriteTours");

                    b.Navigation("ManagedChats");

                    b.Navigation("Messages");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
